<?php

namespace Papir\Crm;

class Router
{
    private $routes = [
        // ── Legacy pages (тимчасово ще використовуються) ─────────────────────
        '/'              => '/pages/warehoses-np.html',   // legacy
        '/warehoses-np'  => '/pages/warehoses-np.html',  // legacy
        '/shiplist-ukr'  => '/pages/shiplist-ukr.html',  // legacy
        '/analitics'     => '/pages/analitics.html',      // legacy
        '/orders'        => '/pages/orders.html',        // legacy
        // ─────────────────────────────────────────────────────────────────────
        '/papir/'           => '/modules/catalog/index.php',
        '/catalog-pricelist' => '/pages/catalog_pricelist.php', // legacy, використовується в /catalog (AJAX)
		'/action'              => '/modules/action/index.php',
		'/action-update-stock' => '/modules/action/update_stock.php',
		'/action-update-site'  => '/modules/action/update_site.php',
		'/catalog'             => '/modules/catalog/index.php',
        '/ttn-ukr.html'             => '/pages/ttn-ukr.html',
		'/manufacturers'                          => '/modules/catalog/manufacturers.php',
		'/category-mapping'                       => '/modules/catalog/category_mapping.php',
		'/catalog/api/get_manufacturers'          => '/modules/catalog/api/get_manufacturers.php',
		'/catalog/api/save_manufacturer'          => '/modules/catalog/api/save_manufacturer.php',
		'/catalog/api/save_manufacturer_record'   => '/modules/catalog/api/save_manufacturer_record.php',
		'/catalog/api/delete_manufacturer'        => '/modules/catalog/api/delete_manufacturer.php',
		'/catalog/api/get_site_categories'        => '/modules/catalog/api/get_site_categories.php',
		'/catalog/api/save_category_mapping'      => '/modules/catalog/api/save_category_mapping.php',
		'/catalog/api/save_product_category'      => '/modules/catalog/api/save_product_category.php',
		'/catalog/api/toggle_site_status'         => '/modules/catalog/api/toggle_site_status.php',
		'/catalog/api/toggle_bk_status'           => '/modules/catalog/api/toggle_bk_status.php',
		'/catalog/api/bulk_toggle_bk_status'      => '/modules/catalog/api/bulk_toggle_bk_status.php',
		'/categories'                             => '/modules/catalog/categories.php',
		'/categories/api/get'                     => '/modules/catalog/api/get_category.php',
		'/categories/api/save'                    => '/modules/catalog/api/save_category.php',
		'/categories/api/save_seo'                => '/modules/catalog/api/save_category_seo.php',
		'/categories/api/add_to_site'             => '/modules/catalog/api/add_category_to_site.php',
		'/categories/api/upload_image'            => '/modules/catalog/api/upload_image.php',
		'/categories/api/delete_image'            => '/modules/catalog/api/delete_image.php',
		'/analytics/google'                       => '/modules/analytics/index.php',
		'/analytics/shopping'                     => '/modules/analytics/shopping.php',
		'/analytics/api/get_report'               => '/modules/analytics/api/get_report.php',
		'/integr/merchant'                        => '/modules/merchant/index.php',
		'/integr/merchant/feed'                   => '/modules/merchant/feed.php',
		'/integr/merchant/feed_mff'               => '/modules/merchant/feed_mff.php',
		'/integr/merchant/api/get_status'         => '/modules/merchant/api/get_status.php',
		'/integr/merchant/api/get_stats'          => '/modules/merchant/api/get_stats.php',
		'/integr/merchant/api/get_autodiscount_stats' => '/modules/merchant/api/get_autodiscount_stats.php',
		'/integr/merchant/api/get_gad_status'        => '/modules/merchant/api/get_gad_status.php',
		'/integr/merchant/api/get_performance'       => '/modules/merchant/api/get_performance.php',
		'/ai'                                     => '/modules/openai/index.php',
		'/ai/api/get_instruction'                 => '/modules/openai/api/get_instruction.php',
		'/ai/api/save_instruction'                => '/modules/openai/api/save_instruction.php',
		'/ai/api/save_settings'                   => '/modules/openai/api/save_settings.php',
		'/ai/api/generate_content'                => '/modules/openai/api/generate_content.php',
		'/ai/api/get_log'                         => '/modules/openai/api/get_log.php',
		'/ai/api/get_log_entry'                   => '/modules/openai/api/get_log_entry.php',
		'/ai/api/delete_logs'                     => '/modules/openai/api/delete_logs.php',
		'/ai/api/get_products_in_category'        => '/modules/openai/api/get_products_in_category.php',
		'/ai/api/search'                          => '/modules/openai/api/search.php',
		'/attributes'                             => '/modules/attributes/index.php',
		'/attributes/api/get'                     => '/modules/attributes/api/get_attributes.php',
		'/attributes/api/get_one'                 => '/modules/attributes/api/get_attribute.php',
		'/attributes/api/save'                    => '/modules/attributes/api/save_attribute.php',
		'/attributes/api/merge'                   => '/modules/attributes/api/merge_attribute.php',
		'/attributes/api/get_values'              => '/modules/attributes/api/get_values.php',
		'/attributes/api/save_value'              => '/modules/attributes/api/save_value.php',
		'/attributes/api/merge_value'             => '/modules/attributes/api/merge_value.php',
		'/attributes/api/save_group'              => '/modules/attributes/api/save_group.php',
		'/image-audit'                            => '/modules/image_audit/index.php',
		'/image-audit/api/action'                 => '/modules/image_audit/api/action.php',
		'/image-audit/api/status'                 => '/modules/image_audit/api/status.php',
		'/shared/api/upload_image'                => '/modules/shared/api/upload_image.php',
		'/shared/api/delete_image'                => '/modules/shared/api/delete_image.php',
		'/shared/api/replace_image'               => '/modules/shared/api/replace_image.php',
		'/shared/api/toggle_image_site'           => '/modules/shared/api/toggle_image_site.php',
		'/prices' => '/modules/prices/index.php',
		'/prices/api/get_product' => '/modules/prices/api/get_product.php',
		'/prices/api/recalculate' => '/modules/prices/api/recalculate_one.php',
		'/prices/api/save_global_settings' => '/modules/prices/api/save_global_settings.php',
		'/prices/api/recalculate_all'      => '/modules/prices/api/recalculate_all.php',
		'/prices/api/save_product_settings' => '/modules/prices/api/save_product_settings.php',
		'/prices/api/bulk_apply_settings' => '/modules/prices/api/bulk_apply_settings.php',
		'/prices/api/save_strategies'     => '/modules/prices/api/save_strategies.php',
		'/prices/api/sync_supplier'       => '/modules/prices/api/sync_supplier.php',
		'/prices/api/save_sheet_config'   => '/modules/prices/api/save_sheet_config.php',
		'/prices/api/match_item'          => '/modules/prices/api/match_item.php',
		'/prices/api/search_catalog'      => '/modules/prices/api/search_catalog.php',
		'/prices/api/toggle_pricelist'    => '/modules/prices/api/toggle_pricelist.php',
		'/prices/api/create_supplier'     => '/modules/prices/api/create_supplier.php',
		'/prices/api/create_pricelist'    => '/modules/prices/api/create_pricelist.php',
		'/prices/api/delete_pricelist'    => '/modules/prices/api/delete_pricelist.php',
		'/prices/api/delete_supplier'     => '/modules/prices/api/delete_supplier.php',
		'/prices/api/update_stock'        => '/modules/prices/api/update_stock.php',
		'/prices/api/save_pricelist_item' => '/modules/prices/api/save_pricelist_item.php',
		'/prices/api/toggle_manual_edit'  => '/modules/prices/api/toggle_manual_edit.php',
		'/prices/api/add_pricelist_item'  => '/modules/prices/api/add_pricelist_item.php',
		'/prices/api/delete_pricelist_item' => '/modules/prices/api/delete_pricelist_item.php',
		'/prices/api/rename_pricelist'      => '/modules/prices/api/rename_pricelist.php',
		'/prices/api/push_prices'           => '/modules/prices/api/push_prices.php',
		'/prices/suppliers'               => '/modules/prices/suppliers.php',
		'/ukrsib_token_status' => '/modules/bank_ukrsib/tools/ukrsib_token_status.php',
		'/ukrsib_token_exchange' => '/modules/bank_ukrsib/tools/ukrsib_token_exchange.php',
		'/payments'              => '/modules/payments_sync/tools/dashboard.php',
		'/finance/bank'          => '/modules/finance/bank.php',
		'/finance/api/save_bank'   => '/modules/finance/api/save_bank.php',
		'/finance/api/delete_bank' => '/modules/finance/api/delete_bank.php',
		'/finance/cash'            => '/modules/finance/cash.php',
		'/finance/api/save_cash'   => '/modules/finance/api/save_cash.php',
		'/finance/api/delete_cash' => '/modules/finance/api/delete_cash.php',
		'/finance/mutual'        => '/modules/finance/mutual.php',
		'/finance/salary'        => '/modules/finance/salary.php',
		'/finance/adjustments'   => '/modules/finance/adjustments.php',
		'/finance/webhook/moysklad' => '/modules/finance/webhook/moysklad.php',
		'/docum/attr' => '/modules/moysklad/tools/dashboard.php',
		'/moysklad/api/webhooks_list'   => '/modules/moysklad/api/webhooks_list.php',
		'/moysklad/api/webhook_create'  => '/modules/moysklad/api/webhook_create.php',
		'/moysklad/api/webhook_delete'  => '/modules/moysklad/api/webhook_delete.php',
		'/counterparties'                         => '/modules/counterparties/index.php',
		'/counterparties/view'                    => '/modules/counterparties/view.php',
		'/counterparties/panel'                   => '/modules/counterparties/panel.php',
		'/counterparties/api/save_counterparty'   => '/modules/counterparties/api/save_counterparty.php',
		'/counterparties/api/save_group'          => '/modules/counterparties/api/save_group.php',
		'/counterparties/api/save_relation'       => '/modules/counterparties/api/save_relation.php',
		'/counterparties/api/delete_relation'     => '/modules/counterparties/api/delete_relation.php',
		'/counterparties/api/search'              => '/modules/counterparties/api/search.php',
		'/counterparties/api/add_activity'        => '/modules/counterparties/api/add_activity.php',
		'/counterparties/api/get_messages'        => '/modules/counterparties/api/get_messages.php',
		'/counterparties/api/send_message'        => '/modules/counterparties/api/send_message.php',
		'/counterparties/api/get_templates'       => '/modules/counterparties/api/get_templates.php',
		'/counterparties/api/save_template'       => '/modules/counterparties/api/save_template.php',
		'/counterparties/api/delete_template'     => '/modules/counterparties/api/delete_template.php',
		'/counterparties/api/ai_suggest'          => '/modules/counterparties/api/ai_suggest.php',
		'/counterparties/api/link_telegram'       => '/modules/counterparties/api/link_telegram.php',
		'/counterparties/api/gmail_auth_setup'    => '/modules/counterparties/api/gmail_auth_setup.php',
		'/counterparties/api/gmail_auth_callback' => '/modules/counterparties/api/gmail_auth_callback.php',
		'/counterparties/api/upload_message_file'    => '/modules/counterparties/api/upload_message_file.php',
		'/counterparties/api/get_inbox'              => '/modules/counterparties/api/get_inbox.php',
		'/counterparties/api/get_tasks'              => '/modules/counterparties/api/get_tasks.php',
		'/counterparties/api/save_task'              => '/modules/counterparties/api/save_task.php',
		'/counterparties/api/done_task'              => '/modules/counterparties/api/done_task.php',
		'/counterparties/api/snooze_task'            => '/modules/counterparties/api/snooze_task.php',
		'/counterparties/api/get_counterparty_detail'=> '/modules/counterparties/api/get_counterparty_detail.php',
		'/counterparties/api/get_lead_detail'        => '/modules/counterparties/api/get_lead_detail.php',
		'/counterparties/api/get_orders'             => '/modules/counterparties/api/get_orders.php',
		'/counterparties/api/get_order_flow'         => '/modules/counterparties/api/get_order_flow.php',
		'/counterparties/api/order_item_update'      => '/modules/counterparties/api/order_item_update.php',
		'/counterparties/api/order_item_delete'      => '/modules/counterparties/api/order_item_delete.php',
		'/counterparties/api/save_order'             => '/modules/counterparties/api/save_order.php',
		'/counterparties/api/save_order_status'        => '/modules/counterparties/api/save_order_status.php',
		'/counterparties/api/cancel_order'             => '/modules/counterparties/api/cancel_order.php',
		'/counterparties/api/save_return_logistics'    => '/modules/counterparties/api/save_return_logistics.php',
		'/counterparties/api/save_delivery_method'   => '/modules/counterparties/api/save_delivery_method.php',
		'/counterparties/api/save_payment_method'    => '/modules/counterparties/api/save_payment_method.php',
		'/counterparties/api/save_order_delivery'    => '/modules/counterparties/api/save_order_delivery.php',
		'/counterparties/api/save_ttn_manual'        => '/modules/counterparties/api/save_ttn_manual.php',
		'/counterparties/api/delete_order_delivery'  => '/modules/counterparties/api/delete_order_delivery.php',
		'/counterparties/api/get_demand_detail'      => '/modules/counterparties/api/get_demand_detail.php',
		'/counterparties/api/save_demand'            => '/modules/counterparties/api/save_demand.php',
		'/counterparties/api/identify_lead'          => '/modules/counterparties/api/identify_lead.php',
		'/counterparties/api/merge_preview'          => '/modules/counterparties/api/merge_preview.php',
		'/counterparties/dedup'                      => '/modules/counterparties/dedup.php',
		'/counterparties/api/find_dedup_groups'      => '/modules/counterparties/api/find_dedup_groups.php',
		'/counterparties/api/merge_dedup'            => '/modules/counterparties/api/merge_dedup.php',
		'/counterparties/api/create_from_lead'       => '/modules/counterparties/api/create_from_lead.php',
		'/counterparties/api/discard_lead'           => '/modules/counterparties/api/discard_lead.php',
		'/counterparties/api/save_reminder'          => '/modules/counterparties/api/save_reminder.php',
		'/counterparties/api/get_employees'          => '/modules/counterparties/api/get_employees.php',
		'/counterparties/api/poll_viber_replies'     => '/modules/counterparties/api/poll_viber_replies.php',
		'/counterparties/api/spam_senders'           => '/modules/counterparties/api/spam_senders.php',
		'/counterparties/api/get_files'              => '/modules/counterparties/api/get_files.php',
		'/counterparties/api/upload_file'            => '/modules/counterparties/api/upload_file.php',
		'/counterparties/api/delete_file'            => '/modules/counterparties/api/delete_file.php',
		'/counterparties/api/download_file'          => '/modules/counterparties/api/download_file.php',
		'/counterparties/api/download_media'         => '/modules/counterparties/api/download_media.php',
		'/counterparties/webhook/moysklad'           => '/modules/counterparties/webhook/moysklad.php',
		'/counterparties/webhook/gmail_push'         => '/modules/counterparties/webhook/gmail_push.php',
		'/counterparties/webhook/viber_in'           => '/modules/counterparties/webhook/viber_in.php',
		'/counterparties/webhook/telegram_in'        => '/modules/counterparties/webhook/telegram_in.php',
		'/counterparties/webhook/telegram_set'       => '/modules/counterparties/webhook/telegram_set.php',
		'/counterparties/webhook/website_form'       => '/modules/counterparties/webhook/website_form.php',
		'/demand'                      => '/modules/demand/index.php',
		'/demand/edit'                 => '/modules/demand/edit.php',
		'/demand/api/sync_one'         => '/modules/demand/api/sync_one.php',
		'/demand/api/save'             => '/modules/demand/api/save_demand.php',
		'/demand/webhook/moysklad'     => '/modules/demand/webhook/moysklad.php',
		'/sales/scenarios'              => '/modules/sales/scenarios.php',
		'/sales/api/save_trigger'       => '/modules/sales/api/save_trigger.php',
		'/sales/api/delete_trigger'     => '/modules/sales/api/delete_trigger.php',
		'/sales/api/delete_scenario'    => '/modules/sales/api/delete_scenario.php',
		'/sales/api/toggle_trigger'     => '/modules/sales/api/toggle_trigger.php',
		'/sales/api/get_trigger'        => '/modules/sales/api/get_trigger.php',
		'/sales/api/get_scenario'       => '/modules/sales/api/get_scenario.php',
		'/sales/api/save_scenario'      => '/modules/sales/api/save_scenario.php',
		'/sales/api/get_queue'          => '/modules/sales/api/get_queue.php',
		'/customerorder' => '/modules/customerorder/index.php',
		'/customerorder/edit' => '/modules/customerorder/edit.php',
		'/customerorder/save' => '/modules/customerorder/save.php',
		'/customerorder/item_add' => '/modules/customerorder/item_add.php',
		'/customerorder/item_delete' => '/modules/customerorder/item_delete.php',
		'/customerorder/item_update' => '/modules/customerorder/item_update.php',
		'/customerorder/search_product' => '/modules/customerorder/search_product.php',
		'/customerorder/item_add_ajax' => '/modules/customerorder/item_add_ajax.php',
		'/customerorder/ajax_get_bank_accounts' => '/modules/customerorder/ajax_get_bank_accounts.php',
		'/customerorder/api/get_linked_docs'    => '/modules/customerorder/api/get_linked_docs.php',
		'/customerorder/api/create_document'      => '/modules/customerorder/api/create_document.php',
		'/customerorder/api/search_linkable_docs' => '/modules/customerorder/api/search_linkable_docs.php',
		'/customerorder/api/link_documents'       => '/modules/customerorder/api/link_documents.php',
		'/customerorder/api/unlink_document'      => '/modules/customerorder/api/unlink_document.php',
		'/customerorder/webhook/moysklad'      => '/modules/customerorder/webhook/moysklad.php',
		'/catalog/api/add_to_site'              => '/modules/catalog/api/add_to_site.php',
		'/catalog/api/set_main_image'           => '/modules/catalog/api/set_main_image.php',
		'/catalog/api/delete_product'           => '/modules/catalog/api/delete_product.php',
		'/catalog/api/save_product_content'     => '/modules/catalog/api/save_product_content.php',
		'/catalog/api/save_product_specs'       => '/modules/catalog/api/save_product_specs.php',
		'/catalog/api/get_product_attributes'   => '/modules/catalog/api/get_product_attributes.php',
		'/catalog/api/save_product_attribute'   => '/modules/catalog/api/save_product_attribute.php',
		'/catalog/api/delete_product_attribute' => '/modules/catalog/api/delete_product_attribute.php',

		// ── Logistics: Nova Poshta ───────────────────────────────────────────────
		'/novaposhta/ttns'                    => '/modules/novaposhta/index.php',
		'/novaposhta/scansheets'              => '/modules/novaposhta/scansheets.php',
		'/novaposhta/print/scansheet'         => '/modules/novaposhta/print_scansheet.php',
		'/novaposhta/senders'                 => '/modules/novaposhta/senders.php',
		'/novaposhta/api/refresh_sender'        => '/modules/novaposhta/api/refresh_sender.php',
		'/novaposhta/api/save_sender_settings'  => '/modules/novaposhta/api/save_sender_settings.php',
		'/novaposhta/api/set_default_address' => '/modules/novaposhta/api/set_default_address.php',
		'/novaposhta/api/set_default_sender'    => '/modules/novaposhta/api/set_default_sender.php',
		'/novaposhta/api/save_contact_person'   => '/modules/novaposhta/api/save_contact_person.php',
		'/novaposhta/api/delete_contact_person' => '/modules/novaposhta/api/delete_contact_person.php',
		'/novaposhta/api/save_sender_address'   => '/modules/novaposhta/api/save_sender_address.php',
		'/novaposhta/api/delete_sender_address' => '/modules/novaposhta/api/delete_sender_address.php',
		'/novaposhta/api/get_ttn_form'        => '/modules/novaposhta/api/get_ttn_form.php',
		'/novaposhta/api/get_senders'         => '/modules/novaposhta/api/get_senders.php',
		'/novaposhta/api/create_ttn'           => '/modules/novaposhta/api/create_ttn.php',
		'/novaposhta/api/get_ttn_detail'       => '/modules/novaposhta/api/get_ttn_detail.php',
		'/novaposhta/api/update_ttn_detail'    => '/modules/novaposhta/api/update_ttn_detail.php',
		'/novaposhta/api/duplicate_ttn'        => '/modules/novaposhta/api/duplicate_ttn.php',
		'/novaposhta/api/add_ttn_to_scansheet' => '/modules/novaposhta/api/add_ttn_to_scansheet.php',
		'/novaposhta/api/delete_ttn'          => '/modules/novaposhta/api/delete_ttn.php',
		'/novaposhta/api/print_ttn_sticker'   => '/modules/novaposhta/api/print_ttn_sticker.php',
		'/novaposhta/api/bulk_delete_ttns'    => '/modules/novaposhta/api/bulk_delete_ttns.php',
		'/novaposhta/api/bulk_print_ttns'     => '/modules/novaposhta/api/bulk_print_ttns.php',
		'/novaposhta/api/track_ttn'           => '/modules/novaposhta/api/track_ttn.php',
		'/novaposhta/api/sync_ttns_quick'     => '/modules/novaposhta/api/sync_ttns_quick.php',
		'/novaposhta/api/set_ttn_order'       => '/modules/novaposhta/api/set_ttn_order.php',
		'/novaposhta/api/get_ttn_list'        => '/modules/novaposhta/api/get_ttn_list.php',
		'/novaposhta/api/get_ttn_table'       => '/modules/novaposhta/api/get_ttn_table.php',
		'/novaposhta/api/search_city'         => '/modules/novaposhta/api/search_city.php',
		'/novaposhta/api/search_warehouse'    => '/modules/novaposhta/api/search_warehouse.php',
		'/novaposhta/api/search_street'       => '/modules/novaposhta/api/search_street.php',
		'/novaposhta/api/create_scansheet'    => '/modules/novaposhta/api/create_scansheet.php',
		'/novaposhta/api/get_scansheats'      => '/modules/novaposhta/api/get_scansheats.php',
		'/novaposhta/api/sync_scansheats'     => '/modules/novaposhta/api/sync_scansheats.php',
		'/novaposhta/api/delete_scansheet'    => '/modules/novaposhta/api/delete_scansheet.php',
		'/novaposhta/api/get_scansheet_ttns'  => '/modules/novaposhta/api/get_scansheet_ttns.php',
		'/novaposhta/api/check_return'           => '/modules/novaposhta/api/check_return.php',
		'/novaposhta/api/create_return'          => '/modules/novaposhta/api/create_return.php',
		'/novaposhta/courier-calls'              => '/modules/novaposhta/courier_calls.php',
		'/novaposhta/api/get_delivery_dates'     => '/modules/novaposhta/api/get_delivery_dates.php',
		'/novaposhta/api/get_time_intervals'     => '/modules/novaposhta/api/get_time_intervals.php',
		'/novaposhta/api/create_courier_call'    => '/modules/novaposhta/api/create_courier_call.php',
		'/novaposhta/api/sync_courier_calls'     => '/modules/novaposhta/api/sync_courier_calls.php',
		'/novaposhta/api/delete_courier_call'    => '/modules/novaposhta/api/delete_courier_call.php',
		'/novaposhta/api/get_courier_call_ttns'  => '/modules/novaposhta/api/get_courier_call_ttns.php',

		'/jobs'          => '/modules/jobs/index.php',
		'/jobs/api/list'     => '/modules/jobs/api/list.php',
		'/jobs/api/status'   => '/modules/jobs/api/status.php',
		'/jobs/api/register' => '/modules/jobs/api/register.php',

		'/system/monitor'            => '/modules/system/monitor.php',
		'/system/api/get_stats'      => '/modules/system/api/get_stats.php',
		'/system/api/run_command'    => '/modules/system/api/run_command.php',
		'/system/api/get_crons'      => '/modules/system/api/get_crons.php',
		'/system/api/get_jobs'       => '/modules/system/api/get_jobs.php',
		'/system/api/get_log'        => '/modules/system/api/get_log.php',
		'/system/api/analyze_log'    => '/modules/system/api/analyze_log.php',
		'/system/api/clear_log'      => '/modules/system/api/clear_log.php',
		'/system/logs'               => '/modules/system/logs.php',
		'/system/sites'              => '/modules/system/sites.php',
		'/system/api/get_site_stats' => '/modules/system/api/get_site_stats.php',
		'/system/api/get_site_log'   => '/modules/system/api/get_site_log.php',
		'/system/backlog'            => '/modules/system/backlog.php',
		'/system/api/backlog_add'    => '/modules/system/api/backlog_add.php',
		'/system/api/backlog_done'   => '/modules/system/api/backlog_done.php',
		'/system/api/backlog_list'   => '/modules/system/api/backlog_list.php',
		'/system/api/backlog_update'            => '/modules/system/api/backlog_update.php',
		'/system/api/backlog_delete'            => '/modules/system/api/backlog_delete.php',
		'/system/api/backlog_upload_screenshot' => '/modules/system/api/backlog_upload_screenshot.php',

		'/system/organizations' => '/modules/print/organizations.php',

		// ── Print / Documents ─────────────────────────────────────────────────
		'/print/templates'              => '/modules/print/templates.php',
		'/print/api/save_template'      => '/modules/print/api/save_template.php',
		'/print/api/render_preview'     => '/modules/print/api/render_preview.php',
		'/print/api/save_organization'  => '/modules/print/api/save_organization.php',
		'/print/api/save_bank_account'  => '/modules/print/api/save_bank_account.php',
		'/print/api/upload_org_asset'   => '/modules/print/api/upload_org_asset.php',
		'/print/api/delete_org_asset'        => '/modules/print/api/delete_org_asset.php',
		'/print/api/set_default_organization' => '/modules/print/api/set_default_organization.php',
		'/print/api/render_doc'         => '/modules/print/api/render_doc.php',
		'/print/api/get_doc_templates'  => '/modules/print/api/get_doc_templates.php',
		'/print/api/invoice_text'       => '/modules/print/api/invoice_text.php',
		'/print/api/generate_order_pdf' => '/modules/print/api/generate_order_pdf.php',

		// ── Auth ──────────────────────────────────────────────────────────────
		'/login'                     => '/modules/auth/login.php',
		'/auth/profile'              => '/modules/auth/profile.php',
		'/auth/users'                => '/modules/auth/users.php',
		'/auth/roles'                => '/modules/auth/roles.php',
		'/auth/api/check_phone'      => '/modules/auth/api/check_phone.php',
		'/auth/api/send_otp'         => '/modules/auth/api/send_otp.php',
		'/auth/api/verify_otp'       => '/modules/auth/api/verify_otp.php',
		'/auth/api/login_password'   => '/modules/auth/api/login_password.php',
		'/auth/api/set_password'     => '/modules/auth/api/set_password.php',
		'/auth/api/logout'           => '/modules/auth/api/logout.php',
		'/auth/api/save_user'        => '/modules/auth/api/save_user.php',
		'/auth/api/delete_user'      => '/modules/auth/api/delete_user.php',
		'/auth/api/save_employee'    => '/modules/auth/api/save_employee.php',
		'/auth/api/save_avatar'      => '/modules/auth/api/save_avatar.php',
		'/auth/api/save_role'        => '/modules/auth/api/save_role.php',
		'/auth/api/save_permissions' => '/modules/auth/api/save_permissions.php',
		'/auth/api/save_profile'     => '/modules/auth/api/save_profile.php',

    ];

    public function handleRequest($requestUri)
    {
        $path = parse_url($requestUri, PHP_URL_PATH);
        $filePath = $this->resolveRoute($path);

        if ($filePath) {
            require __DIR__ . '/../' . $filePath;
        } else {
            http_response_code(404);
            require __DIR__ . '/../pages/page-404.html';
        }
    }

    // Функция для поиска маршрута с поддержкой .html и без него
	private function resolveRoute($path)
	{
		if ($path !== '/') {
			$path = rtrim($path, '/');
		}

		if (array_key_exists($path, $this->routes)) {
			return $this->routes[$path];
		}

		$pathWithoutHtml = preg_replace('/\.html$/', '', $path);
		if (array_key_exists($pathWithoutHtml, $this->routes)) {
			return $this->routes[$pathWithoutHtml];
		}

		return null;
	}

}
